### ISSUE TITLE
SPIKE側のプログラムを実行してからの時間制限

### ISSUE THREAD

**Issue by karubehub** [ytoi/ev3rt_aspsim_raspi_linux#11]
これは、問題ではないかもしれませんが、

SPIKE側のプログラムを実行して、”ET”と表示されてから、
およそ、1分55秒〜58秒程度で、動きが止まるのですが、
これは、競技ルール上の2分の成約条件によるものでしょうか？

例えば、SPIKE側のプログラムを実行して、”ET”と表示されてから、
30秒後に、EV3RT側のプログラムを実行すると、動作可能時間は
2分ー30秒＝1分30秒間になります。

**Comment by ytoi** [comment]
今は評価ようにプログラム起動してから2分で止めるようにしていましたが、制限を解除します

**Comment by ytoi** [comment]
とりあえず10分動作するようにします（あまり長くしても、pythonのgcで動作が遅くなるため)
